axes_linear:
  x: 7
  y: 6
scale_linear:
  x: 10
  y: 12
buttons_angular:
  left: 4
  right: 5
scale_angular: 10
button_enable_continuous_mode: 7
button_disable_continuous_mode: 6
button_motions:
  left_kick:
    axis: 2
    axis_threshold: -1.0
    motion_id: 33
  right_kick:
    axis: 5
    axis_threshold: -1.0
    motion_id: 32
  front_stand_up:
    button: 3
    motion_id: 3
  back_stand_up:
    button: 0
    motion_id: 4
  side_stand_up_left:
    button: 2
    motion_id: 6
  side_stand_up_right:
    button: 1
    motion_id: 7
